version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}  # Set your password
      POSTGRES_DB: ${POSTGRES_DB}              # Set your database name
      POSTGRES_USER: ${POSTGRES_USER}      # Set your username
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
